doctest:
  build_args:
    - "-DDOCTEST_WITH_TESTS=OFF"
libyang:
  build_args:
    - "-DENABLE_VALGRIND_TESTS=ON"
    - "-DENABLE_TESTS=ON"
libyang-cpp:
  build_args: [ ]
libnetconf2:
  build_args:
    - "-DENABLE_VALGRIND_TESTS=ON"
libnetconf2-cpp:
  build_args: [ ]
replxx:
  build_args: [ ]
docopt.cpp:
  build_args: [ ]
trompeloeil:
  build_args:
    - "-DCMAKE_BUILD_TYPE=Release"
sysrepo:
  build_args:
    - "-DENABLE_TESTS=ON"
    - "-DENABLE_VALGRIND_TESTS=ON"
sysrepo-cpp:
  build_args: [ ]
Netopeer2:
  build_args:
    - "-DENABLE_TESTS=ON"
    - "-DENABLE_VALGRIND_TESTS=ON"
    - "-DINSTALL_MODULES=ON"
    - "-DGENERATE_HOSTKEYS=ON"
    - "-DMERGE_LISTEN_CONFIG=ON"

