version: 1
disable_existing_loggers: False
formatters:
  consoleFormatter:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%d-%b-%y %H:%M:%S'
  fileFormatter:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%d-%b-%y %H:%M:%S'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: consoleFormatter
    stream: ext://sys.stdout
  fileHandler:
    class: logging.FileHandler
    level: DEBUG
    formatter: fileFormatter
    filename: null
    mode: w
loggers:
  root:
    level: DEBUG
    handlers: [ consoleHandler, fileHandler ]
